### ISSUE TITLE
Installation guide needs an update

### ISSUE THREAD

**Issue by YutMarma** [OPSnet/Logchecker#14]
The installation guide makes reference to a "logchecker.phar" file on the Releases tab, but the most recent release which includes a .phar is 0.9.7 - either the installation guide should be updated, or more recent releases should include the .phar.

**Comment by itismadness** [comment]
Thanks for pointing this out. Creating the phar archives as part of the release process was lost in the transition to GH actions from travis in 446ce58d9469ccfb7ab5408abe5d0bac2ce5c487.

I've added a new workflow that should handle this (35240df211e81f92ec14d01ffb52bb9c8b826021) going forward, and I've gone back and generated the `logchecker.phar` file for the releases that were missing it. I've also updated the README a bit since there were a handful of places that were out of date.
